### ISSUE TITLE
点击事件

### ISSUE THREAD

**Issue by 2435324075** [wwmz/WMZTreeView#10]
最后一级选中/取消选中的点击事件能不能加到整个cell上面
[self.check addTarget:self action:@selector(checkAction:) forControlEvents:UIControlEventTouchUpInside];

**Comment by wwmz** [comment]
你可以自定义cell呢 把我这个cell的内容复制到你自定义cell里就可以了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mumu <notifications@github.com&gt;
发送时间: 2020年8月31日 16:46
收件人: wwmz/WMZTreeView <WMZTreeView@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[wwmz/WMZTreeView] 点击事件 (#10)





 
最后一级选中/取消选中的点击事件能不能加到整个cell上面
 [self.check addTarget:self action:@selector(checkAction:) forControlEvents:UIControlEventTouchUpInside];
