### ISSUE TITLE
你好,添加子节点后能不能加个方法自动展开?

### ISSUE THREAD

**Issue by lixiangshadow** [wwmz/WMZTreeView#13]
你好,添加子节点后能不能加个方法自动展开?

**Comment by wwmz** [comment]
> 你好,添加子节点后能不能加个方法自动展开?

最近找时间加

**Comment by yangdengxueshi** [comment]
添加子节点后加个方法自动展开,这是一个刚需功能,添加一下吧

**Comment by wwmz** [comment]
> 添加子节点后加个方法自动展开,这是一个刚需功能,添加一下吧

增加了

**Comment by wwmz** [comment]
> 你好,添加子节点后能不能加个方法自动展开?

增加了

**Comment by yangdengxueshi** [comment]
谢谢作者

**Comment by yangdengxueshi** [comment]
@wwmz 
pod WMZTreeView 还没有更新吗? 目前还是1.0.3

**Comment by wwmz** [comment]
> @wwmz
> pod WMZTreeView 还没有更新吗? 目前还是1.0.3

没 先拉进去吧 改动比较小 就没更了哈哈

**Comment by yangdengxueshi** [comment]
@wwmz    

希望更新到 pod 中,便于集中管理(== 我比较懒)哈哈😄.

**Comment by yangdengxueshi** [comment]
还是更新一下 pod 吧, 不少人用的 Swift 写程序的

**Comment by yangdengxueshi** [comment]
@wwmz 

还是更新一下 pod 吧, 不少人用的 Swift 写程序的
