### ISSUE TITLE
搜索功能

### ISSUE THREAD

**Issue by mrkison** [wwmz/WMZTreeView#15]
请问怎么添加搜索，reload更新搜索结果数据

**Comment by mrkison** [comment]
1、怎么判断是子节点。
2、当前节点的children.count可能是0，但是当前节点任然是属于非子节点，应该可以点击切换箭头向下，只是没有子节点。
应该加一个是否是子节点的属性，判断。

**Comment by wwmz** [comment]
> 1、怎么判断是子节点。
> 2、当前节点的children.count可能是0，但是当前节点任然是属于非子节点，应该可以点击切换箭头向下，只是没有子节点。
> 应该加一个是否是子节点的属性，判断。

有parentId即为子节点

**Comment by mrkison** [comment]
我的意思是，最后一级节点。

**Comment by mrkison** [comment]
> > 1、怎么判断是子节点。
> > 2、当前节点的children.count可能是0，但是当前节点任然是属于非子节点，应该可以点击切换箭头向下，只是没有子节点。
> > 应该加一个是否是子节点的属性，判断。
> 
> 有parentId即为子节点

我的意思是，判断是，最后一级节点

**Comment by wwmz** [comment]
> > > 1、怎么判断是子节点。
> > > 2、当前节点的children.count可能是0，但是当前节点任然是属于非子节点，应该可以点击切换箭头向下，只是没有子节点。
> > > 应该加一个是否是子节点的属性，判断。
> > 
> > 
> > 有parentId即为子节点
> 
> 我的意思是，判断是，最后一级节点

没必要 最后一级都没子节点了 还要加个箭头向下去误导人去点？

**Comment by wwmz** [comment]
> > > 1、怎么判断是子节点。
> > > 2、当前节点的children.count可能是0，但是当前节点任然是属于非子节点，应该可以点击切换箭头向下，只是没有子节点。
> > > 应该加一个是否是子节点的属性，判断。
> > 
> > 
> > 有parentId即为子节点
> 
> 我的意思是，判断是，最后一级节点

你见过哪个是最后一级没子节点了 还有个箭头让人去点的吗。。

**Comment by mrkison** [comment]
> > > > 1、怎么判断是子节点。
> > > > 2、当前节点的children.count可能是0，但是当前节点任然是属于非子节点，应该可以点击切换箭头向下，只是没有子节点。
> > > > 应该加一个是否是子节点的属性，判断。
> > > 
> > > 
> > > 有parentId即为子节点
> > 
> > 
> > 我的意思是，判断是，最后一级节点
> 
> 你见过哪个是最后一级没子节点了 还有个箭头让人去点的吗。。

1、主要是有一个通讯录需求，因为需要创建了一个通讯录分类，但是还没有添加人员，这时还是要求是非最后一级的样式，但现在这一级最后children.count为0。（可以展开的cell和最后一级人员的cell样式差别比较大）。
2、还有，有个搜索功能，请问有搜索后只更新数据源的方法么，还是只能重新创建。
谢谢。
