### ISSUE TITLE
数据重复

### ISSUE THREAD

**Issue by mrkison** [wwmz/WMZTreeView#16]
大佬，我在做搜索功能时，移除tree再添加后，数据会一直双倍增加。请问这是为什么？
if (TF.text.length%2 == 1) {
//销毁
        [self.treeView removeFromSuperview];
        self.treeView = nil;
    }else {
//添加
        [self addTree];
    }

**Comment by wwmz** [comment]
> 大佬，我在做搜索功能时，移除tree再添加后，数据会一直双倍增加。请问这是为什么？
> if (TF.text.length%2 == 1) {
> //销毁
> [self.treeView removeFromSuperview];
> self.treeView = nil;
> }else {
> //添加
> [self addTree];
> }

重新设置一下treeview.param.wData 然后调用[treeview update] 方法

**Comment by mrkison** [comment]
> > 大佬，我在做搜索功能时，移除tree再添加后，数据会一直双倍增加。请问这是为什么？
> > if (TF.text.length%2 == 1) {
> > //销毁
> > [self.treeView removeFromSuperview];
> > self.treeView = nil;
> > }else {
> > //添加
> > [self addTree];
> > }
> 
> 重新设置一下treeview.param.wData 然后调用[treeview update] 方法

- (void)searchTFTextChange:(UITextField *)TF {
    //FIXME:数据重复
    if (TF.text.length == 0) {
        self.treeView.param.wData = self.dataMArr;
    }else {
        NSPredicate *predicate = [NSPredicate predicateWithFormat:@"data.name contains %@ or data.phone contains %@ or data.roleName contains %@ or data=nil", TF.text, TF.text, TF.text];
        self.treeView.param.wData = [NSMutableArray arrayWithArray:[self.dataMArr filteredArrayUsingPredicate:predicate]];
    }
    [self.treeView update];
}
这样写也会增加双倍数据，

**Comment by mrkison** [comment]
我断点看了，此时 wData 只有5个数据
_wData    __NSArrayM *    @"5 elements"    0x0000600000fa15f0
但是data里有很多数据
_data    __NSArrayM *    @"22 elements"    0x0000600000e004b0
