### ISSUE TITLE
怎么能做到默认展开某一个父类及他的子类 ，不是全部展开

### ISSUE THREAD

**Issue by tanghk** [wwmz/WMZTreeView#17]

**Comment by wwmz** [comment]
> _No description provided._

设置子数据源 isExpand 为yes试试

**Comment by tanghk** [comment]
尝试了 但是没有作用

**Comment by wwmz** [comment]
> 尝试了 但是没有作用

你没设置对吧 你要把全部展开那个属性关了  然后子数据源从第一级开始 都要        isExpandSet为YES 类似这样哦
TreeParam().isExpandSet(YES) .currentIdSet(@"1").nameSet(@"第1_0级")
TreeParam().isExpandSet(YES).currentIdSet(@"11").nameSet(@"第2_11级").parentIdSet(@"1"),
TreeParam().isExpandSet(YES).currentIdSet(@"111").nameSet(@"第3_111级").parentIdSet(@"11"),

**Comment by tanghk** [comment]
我设置的问题，非常感谢

**Comment by tanghk** [comment]
有个新的问题 知道了子类的节点，怎么让他的父类都处于产开状态
