### ISSUE TITLE
有三级树状选中两个第三级，后面取消第三级的其中一个，然后第一级和第二级就变成不选中的了，这个怎么解决？

### ISSUE THREAD

**Issue by qz-wzf** [wwmz/WMZTreeView#19]
<img width="638" alt="截屏2021-04-27 上午11 51 09" src="https://user-images.githubusercontent.com/22139358/116182474-e79c4d00-a74e-11eb-986a-baf203e8f386.png">

**Comment by wwmz** [comment]
wCheckStrictly
