### ISSUE TITLE
删掉默认的灰色背景吧

### ISSUE THREAD

**Issue by yangdengxueshi** [wwmz/WMZTreeView#20]
WMZTreeBaseView.m 中

`- (UITableView *)table{
    if (!_table) {
        _table = [[UITableView alloc]initWithFrame:self.bounds style:UITableViewStyleGrouped];

	_table.backgroundColor = UIColor.clearColor;  // 增加当前行,删掉默认的灰色背景

        _table.estimatedRowHeight = 100;
        if (@available(iOS 11.0, *)) {
            _table.estimatedSectionFooterHeight = 0.01;
            _table.estimatedSectionHeaderHeight = 0.01;
            _table.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
        }
       _table.delegate = (id)self;
       _table.dataSource = (id)self;
    }
    return _table;
}`

**Comment by wwmz** [comment]
> WMZTreeBaseView.m 中
> 
> `- (UITableView *)table{
> if (!_table) {
> _table = [[UITableView alloc]initWithFrame:self.bounds style:UITableViewStyleGrouped];
> 
> ```
> _table.backgroundColor = UIColor.clearColor;  // 增加当前行,删掉默认的灰色背景
> 
> 
>     _table.estimatedRowHeight = 100;
>     if (@available(iOS 11.0, *)) {
>         _table.estimatedSectionFooterHeight = 0.01;
>         _table.estimatedSectionHeaderHeight = 0.01;
>         _table.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
>     }
>    _table.delegate = (id)self;
>    _table.dataSource = (id)self;
> }
> return _table;
> ```
> 
> }`

啊哈 这个无所谓吧

**Comment by yangdengxueshi** [comment]
有所谓的, 我们可以自定义单元格来设置背景, 你这个默认背景严重影响用户观感

**Comment by yangdengxueshi** [comment]
只需要加入这行去掉默认灰色背景就行了

_table.backgroundColor = UIColor.clearColor;  // 增加当前行,删掉默认的灰色背景

有灰色用户不爽啊

**Comment by wwmz** [comment]
> 只需要加入这行去掉默认灰色背景就行了
> 
> _table.backgroundColor = UIColor.clearColor; // 增加当前行,删掉默认的灰色背景
> 
> 有灰色用户不爽啊
嗯 自己修改一下源码就行了 或者外部直接set value

**Comment by wwmz** [comment]
> 有所谓的, 我们可以自定义单元格来设置背景, 你这个默认背景严重影响用户观感

嗯 自己修改一下源码就行了 或者外部直接set value

**Comment by yangdengxueshi** [comment]
![Screen Shot 2021-09-09 at 17 44 07](https://user-images.githubusercontent.com/25955707/132663439-14b1d54d-5c44-4f71-9f17-08a3ed1e769c.png)


用户就接受不了我这个区域树有灰色背景,我现在是改的源代码

**Comment by yangdengxueshi** [comment]
> > 有所谓的, 我们可以自定义单元格来设置背景, 你这个默认背景严重影响用户观感
> 
> 嗯 自己修改一下源码就行了 或者外部直接set value

外部修改不得行,修改源码才行

**Comment by yangdengxueshi** [comment]
> > > 有所谓的, 我们可以自定义单元格来设置背景, 你这个默认背景严重影响用户观感
> > 
> > 
> > 嗯 自己修改一下源码就行了 或者外部直接set value
> 
> 外部修改不得行,修改源码才行

我试过了,修改源码是可以的,外部修改无效
