### ISSUE TITLE
cocoapod找不到库

### ISSUE THREAD

**Issue by lszHub** [wwmz/WMZTreeView#4]
更新了pod也找不到，不知道是什么原因

**Comment by wwmz** [comment]
> 更新了pod也找不到，不知道是什么原因

你先在本地 pod search WMZDialog
如果search不到 代表不是本地pod不是最新
前往~/Library/Caches/CocoaPods/search_index.json 删除（search_index.json）
然后继续 pod search WMZDialog 等待 应该就可以找到了

**Comment by wwmz** [comment]
> 更新了pod也找不到，不知道是什么原因

你先在本地 pod search WMZTreeView
如果search不到 代表不是本地pod不是最新
前往~/Library/Caches/CocoaPods/search_index.json 删除（search_index.json）
然后继续 pod search WMZTreeView 等待 应该就可以找到了
