### ISSUE TITLE
请问选择结果怎么到导出

### ISSUE THREAD

**Issue by harveyseeking** [wwmz/WMZTreeView#6]
我想把勾选的结果保存或上传服务器，要怎么获取到选择到结果呢

**Comment by wwmz** [comment]
> 我想把勾选的结果保存或上传服务器，要怎么获取到选择到结果呢
实例方法有 你点头文件进去看就知道了
/*
 *获取当前选中的节点数组
 @param halfSelect 包含半选中
 @return NSArray 返回数组
 */
- (NSArray*)getCheckedNodesWithHalfSelect:(BOOL)halfSelect;

**Comment by harveyseeking** [comment]
好的谢谢大神

**Comment by harveyseeking** [comment]
请问有没有方法可以即显示勾选按钮又不让进行勾选呢，就只是查看勾选的情况

**Comment by wwmz** [comment]
> 请问有没有方法可以即显示勾选按钮又不让进行勾选呢，就只是查看勾选的情况

我里面有写不可选中逻辑的 不过我是不让进行勾选就隐藏掉了 我加个属性吧 wShowOnly 设置为YES的时候 就canSelect为NO的数据勾选按钮就展示出来了

**Comment by harveyseeking** [comment]
大神你太厉害了
