### ISSUE TITLE
更新数据

### ISSUE THREAD

**Issue by feelingstack** [wwmz/WMZTreeView#7]
请问使用setParam更新数据之后，再使用WMZTreeView里面update方法更新，结果只是在原有基础上添加，有办法释放掉之前加载的数据吗？

**Comment by feelingstack** [comment]
重新设置param之前，需要将里面的数据清掉，可以在WMZTreeView里卖弄添加一个方法，加入[self.data removeAllObjects],再更新数据即可。

**Comment by wwmz** [comment]
嗯 方法已加上
