### ISSUE TITLE
请问一下 怎么获取当前节点的父节点

### ISSUE THREAD

**Issue by qllqll** [wwmz/WMZTreeView#8]
大佬，请问一下 怎么获取当前节点的父节点

**Comment by wwmz** [comment]
> 大佬，请问一下 怎么获取当前节点的父节点

/*
*获取父节点
*/
- (WMZTreeParam*)getParentId:(NSString*)currrentID;

**Comment by qllqll** [comment]
感谢了哈，我也找到了

**Comment by tanghk** [comment]
有个新的问题 知道了子类的节点，怎么让他的父类都处于产开状态

**Comment by wwmz** [comment]
> 有个新的问题 知道了子类的节点，怎么让他的父类都处于产开状态

设置isExpand
