### ISSUE TITLE
数据排序问题

### ISSUE THREAD

**Issue by CC10559** [wwmz/WMZTreeView#9]
数据到底是根据什么来排序的啊,我递归好的数据,传进来,展示就乱了

**Comment by CC10559** [comment]
在WMZTreeBaseView.m里面
- (NSMutableArray*)getSonData:(WMZTreeParam*)node type:(TreeDataType)type 这个方法

**Comment by wwmz** [comment]
> 数据到底是根据什么来排序的啊,我递归好的数据,传进来,展示就乱了

？这是啥 已经安装你顺序排的了
